spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false  #使用数值timestamp表示日期，true时会忽略date-format
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_db?rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis.configuration.mapUnderscoreToCamelCase: true

logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.pogong: TRACE
