spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false  #使用数值timestamp表示日期，true时会忽略date-format

  cache:
    redis:
      time-to-live: 3600s

  redis:
    host: 127.0.0.1
    port: 6379
    max-active: 8
    max-wait: 10000
    max-idle: 10

data:
    url: jdbc:mysql://localhost:3306/jdbc_db?rewriteBatchedStatements=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: target/app.log
  level:
    ROOT: WARN
    com.pogong: TRACE
